language: python
# command to install dependencies
install:
  - pip install tox
# # command to run tests
script: tox
after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=traduki --cov-report=term-missing tests
  - coveralls
notifications:
    email:
        - opensource-tests@paylogic.com
